{% set name = "pywr" %}
{% set version = "1.5.0" %}
{% set sha256 = "90e14e85f8255f710cfad0ec188c264fe55a066b9cf7f1e47d993db9d8e75155" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  skip: True  # [py<36]
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
    - {{ compiler('c') }}
    - numpy
    - cython
    - packaging
    - glpk
    - lp_solve
    - future
    - packaging
    - setuptools
    - setuptools_scm
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - pandas
    - networkx
    - glpk
    - lp_solve
    - pytables
    # Fix pytables on windows. See https://github.com/conda-forge/pytables-feedstock/issues/31#issuecomment-410695814
    - snappy  # [win]
    - xlrd
    - scipy
    - future
    - packaging
    - jupyter
    - matplotlib-base

test:
  imports:
    - pywr
    - pywr.core

about:
  home: http://github.com/pywr/pywr
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE.txt
  summary: 'Pywr is a generalised network resource allocation model written in Python'
  description: |
    Pywr is a tool for solving network resource allocation problems at
    discrete timesteps using a linear programming approach. It's principal
    application is in resource allocation in water supply networks, although
    other uses are conceivable. It uses Cython extensions for computational
    efficiency.
  doc_url: https://pywr.github.io/pywr-docs/index.html
  dev_url: http://github.com/pywr/pywr

extra:
  recipe-maintainers:
    - jetuk
