travis:
  secure:
    BINSTAR_TOKEN: W18iNHN/PNGs1THXJXheT/wH03FSnTTBVCUm9/4UaZ00A2OCg0KxKCuPG0p8dWqFR0VHKyh3KM3HjALi3nCXCI93UEBRvTXWRYgPYR1ARZipjPtsgcZkkY3J0HkewRMQv1mObREVi2m6JSEEeywPf0Cy/ycKq9IWorKWxqn5d5FnZV2oFOYJDeFbeXlziFazA0CmN/TigWWscpiXYx3bXrLjNVVEWCK4qhmf4EWrpjftmFM473B8D6yHSAgcbpLrDSCO+wfKRhvJNG2nJI59AyVoNdAZRpDPTDsgFxIYNcJDMF9Elxr5pdMJwFTWGD/A93bHo1bQrgKYVi0B3VyXb9aLk0NCHgwF6MxjEByAwGE87a2wtInAlNHOUcbZEFLRKrHzOsb/ie+1he/I+UiNlEKr86GYvFcxXJNX0tLlg0PodA3hQUJ0RU7h67Bnf7aSYWcXtmDB+Y2BpUWciaoiGA5h+OiKChxv/DnFUJ6BmDgvH0gwW9BGrKfDdWWDK4FiuX0ZC9F6dCemfg2/+ehD+/BcgTWUTQLi2MeLdRt3vT535AHWYZjQrTWvLwHIEO4ZbXn3OECoX5p8kaMAON7qc9UJCWyMJMc4c9Ps2rod1iKNV445P9Rj9m5VEpkY0pGlEB1e6RDfcQbmebM62ly3p8sd0igsH0BvL/BV+fGRCTo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
